name: pipeline
on: [push, pull_request]

jobs:
  pipeline:
    env:
      CI: true
    name: pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint:ts
          yarn lint:css
          yarn lint:style

      - name: Build
        run: yarn build
        env:
          API_URL: ${{ secrets.API_URL }}
          API_PROJECT: ${{ secrets.API_PROJECT }}
          API_EMAIL: ${{ secrets.API_EMAIL }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
